version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
      - mkdir test-reports
  build:
    commands:
      - python -m pytest --junitxml=test-reports/report.xml

reports:
  pytest_reports:
    files:
      - report.xml
    base-directory: test-reports
    file-format: JunitXml

artifacts:
  files:
    - '**/*'
